"""The published deployment.

The Vercel build is the always-on public URL, and it runs the app in a
different shape: no background worker, no persistent disk, so the upload runs
the pipeline inline and returns the finished result in the same response. That
path has its own way to break, so it is tested rather than assumed — together
with the edge-served copy of the interface, which is a mirror of `app/web/`
and is only correct while it stays byte-identical.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent


# ------------------------------------------------------- the static mirror
def test_the_edge_copy_of_the_interface_matches_the_served_one():
    """`public/` is what Vercel's CDN serves and `app/web/` is what the
    FastAPI app serves. If they drift, the deployed interface silently stops
    matching the one that was tested. Regenerate with
    `python -m scripts.build_static`."""
    source, mirror = ROOT / "app" / "web", ROOT / "public"
    assert mirror.exists(), "public/ is missing — run `python -m scripts.build_static`"

    def digests(root: Path) -> dict[str, str]:
        return {
            str(path.relative_to(root)): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in sorted(root.rglob("*"))
            if path.is_file()
        }

    assert digests(source) == digests(mirror), (
        "public/ has drifted from app/web/ — run `python -m scripts.build_static`"
    )


def test_the_interface_needs_no_build_step_and_no_third_party_script():
    """No framework, no CDN: three files served by the same process as the
    API. A blocked CDN must never be able to take the interface down."""
    markup = (ROOT / "app" / "web" / "index.html").read_text(encoding="utf-8")
    assert "http://" not in markup
    assert "https://" not in markup
    for asset in ("/static/app.js", "/static/styles.css", "/static/demo-data.js"):
        assert asset in markup


def test_the_offline_sample_is_the_pipeline_own_output():
    """`demo-data.js` is generated by `python -m tools.make_demo`. Regenerating
    it must be a no-op — otherwise the example in the interface is showing
    something the pipeline no longer produces."""
    import json

    from tools.make_demo import HEADER, TARGET, build

    expected = HEADER + json.dumps(build(), indent=1, ensure_ascii=False) + ";\n"
    assert TARGET.read_text(encoding="utf-8") == expected, (
        "the demo sample no longer matches the pipeline — run `python -m tools.make_demo`"
    )


# --------------------------------------------------- the serverless shape
@pytest.fixture
def serverless_client(tmp_path, monkeypatch):
    """The app as the Vercel entry point configures it."""
    import importlib

    from fastapi.testclient import TestClient

    from app.core.crypto import generate_service_key

    monkeypatch.setenv("SYNCHRONOUS_JOBS", "true")
    monkeypatch.setenv("DEMO_MODE_LITE", "true")
    monkeypatch.setenv("DATA_DIR", str(tmp_path / "serverless"))
    monkeypatch.setenv("ENCRYPTION_KEY", generate_service_key())
    monkeypatch.setenv("AUDIT_LOG_ENABLED", "false")

    import app.config as config

    config.get_settings.cache_clear()
    import app.main as main

    importlib.reload(main)
    with TestClient(main.app) as client:
        yield client
    config.get_settings.cache_clear()


def test_the_upload_returns_the_finished_result_in_one_round_trip(serverless_client):
    """No queue and no polling: the interface reads `result` off the upload
    response and renders straight away."""
    response = serverless_client.post(
        "/v1/jobs",
        files={"file": ("meeting.wav", b"RIFF$\x00\x00\x00WAVEfmt ", "audio/wav")},
        data={"consent": "true"},
    )
    assert response.status_code == 202
    body = response.json()

    assert body["state"] == "completed"
    assert "result" in body, "the serverless build must not ask the browser to poll"

    result = body["result"]
    assert result["transcript"]["utterances"]
    assert result["job"]["stages"], "the interface renders these five stages"
    assert result["quality"]["grounded_claims"] > 0
    assert result["privacy"]["consent"] is True
    assert result["privacy"]["retention_hours"] == 24


def test_the_serverless_build_still_enforces_consent(serverless_client):
    response = serverless_client.post(
        "/v1/jobs",
        files={"file": ("meeting.wav", b"RIFF", "audio/wav")},
        data={"consent": "false"},
    )
    assert response.status_code == 403


def test_the_serverless_build_still_says_it_is_running_scripted_models(serverless_client):
    """The interface reads this and badges itself. Telling someone a scripted
    sample is their meeting would be a lie."""
    assert serverless_client.get("/v1/capabilities").json()["demo_mode"] is True


def test_the_vercel_entry_point_imports_and_exposes_the_app(monkeypatch, tmp_path):
    """Loaded by path, the way Vercel loads it — `api/` is a function
    directory, not an importable package."""
    import importlib.util

    monkeypatch.setenv("DATA_DIR", str(tmp_path / "vercel"))

    spec = importlib.util.spec_from_file_location("vercel_entry", ROOT / "api" / "index.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    assert hasattr(module, "app"), "Vercel expects a module-level `app`"
    # The entry point is what puts the deployment into its serverless shape.
    assert module.os.environ["SYNCHRONOUS_JOBS"] == "true"
    assert module.os.environ["ENCRYPTION_KEY"]
