"""The published deployment.

The Vercel build is the always-on public URL, and it runs the app in a
different shape: no background worker, no persistent disk, so the upload runs
the pipeline inline and returns the finished result in the same response. That
path has its own way to break, so it is tested rather than assumed — together
with the edge-served copy of the interface, which is a mirror of `app/web/`
and is only correct while it stays byte-identical.
"""

from __future__ import annotations

import asyncio
import hashlib
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent


# ------------------------------------------------------- the static mirror
def test_the_edge_copy_of_the_interface_matches_the_served_one():
    """`public/` is what Vercel's CDN serves and `app/web/` is what the
    FastAPI app serves. If they drift, the deployed interface silently stops
    matching the one that was tested. Regenerate with
    `python -m scripts.build_static`."""
    source, mirror = ROOT / "app" / "web", ROOT / "public"
    assert mirror.exists(), "public/ is missing — run `python -m scripts.build_static`"

    def digests(root: Path) -> dict[str, str]:
        return {
            str(path.relative_to(root)): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in sorted(root.rglob("*"))
            if path.is_file()
        }

    assert digests(source) == digests(mirror), (
        "public/ has drifted from app/web/ — run `python -m scripts.build_static`"
    )


def test_the_interface_needs_no_build_step_and_no_third_party_script():
    """No framework, no CDN: three files served by the same process as the
    API. A blocked CDN must never be able to take the interface down."""
    markup = (ROOT / "app" / "web" / "index.html").read_text(encoding="utf-8")
    assert "http://" not in markup
    assert "https://" not in markup
    for asset in ("/static/app.js", "/static/styles.css", "/static/demo-data.js"):
        assert asset in markup


def test_the_offline_sample_is_the_pipeline_own_output():
    """`demo-data.js` is generated by `python -m tools.make_demo`. Regenerating
    it must be a no-op — otherwise the example in the interface is showing
    something the pipeline no longer produces."""
    import json

    from tools.make_demo import HEADER, TARGET, build

    expected = HEADER + json.dumps(build(), indent=1, ensure_ascii=False) + ";\n"
    assert TARGET.read_text(encoding="utf-8") == expected, (
        "the demo sample no longer matches the pipeline — run `python -m tools.make_demo`"
    )


# --------------------------------------------------- the serverless shape
@pytest.fixture
def serverless_client(tmp_path, monkeypatch):
    """The app as the Vercel entry point configures it."""
    import importlib

    from fastapi.testclient import TestClient

    from app.core.crypto import generate_service_key

    monkeypatch.setenv("SYNCHRONOUS_JOBS", "true")
    monkeypatch.setenv("DEMO_MODE_LITE", "true")
    monkeypatch.setenv("DATA_DIR", str(tmp_path / "serverless"))
    monkeypatch.setenv("ENCRYPTION_KEY", generate_service_key())
    monkeypatch.setenv("AUDIT_LOG_ENABLED", "false")

    import app.config as config

    config.get_settings.cache_clear()
    import app.main as main

    importlib.reload(main)
    with TestClient(main.app) as client:
        yield client
    config.get_settings.cache_clear()


def test_the_upload_returns_the_finished_result_in_one_round_trip(serverless_client):
    """No queue and no polling: the interface reads `result` off the upload
    response and renders straight away."""
    response = serverless_client.post(
        "/v1/jobs",
        files={"file": ("meeting.wav", b"RIFF$\x00\x00\x00WAVEfmt ", "audio/wav")},
        data={"consent": "true"},
    )
    assert response.status_code == 202
    body = response.json()

    assert body["state"] == "completed"
    assert "result" in body, "the serverless build must not ask the browser to poll"

    result = body["result"]
    assert result["transcript"]["utterances"]
    assert result["job"]["stages"], "the interface renders these five stages"
    assert result["quality"]["grounded_claims"] > 0
    assert result["privacy"]["consent"] is True
    assert result["privacy"]["retention_hours"] == 24


def test_the_api_works_on_a_host_that_never_runs_lifespan(tmp_path, monkeypatch):
    """Vercel's Python runtime does not emit ASGI lifespan events, so startup
    never runs there and `app.state.services` is never set. Every /v1/ route
    then died with AttributeError and the interface reported the API as
    unreachable — while the static page, served from the CDN, looked fine.

    A TestClient used without its context manager reproduces exactly that.
    """
    import importlib

    from fastapi.testclient import TestClient

    from app.core.crypto import generate_service_key

    monkeypatch.setenv("SYNCHRONOUS_JOBS", "true")
    monkeypatch.setenv("DEMO_MODE_LITE", "true")
    monkeypatch.setenv("AUDIT_LOG_ENABLED", "false")
    monkeypatch.setenv("DATA_DIR", str(tmp_path / "no-lifespan"))
    monkeypatch.setenv("ENCRYPTION_KEY", generate_service_key())

    import app.config as config

    config.get_settings.cache_clear()
    import app.main as main

    importlib.reload(main)

    client = TestClient(main.app)          # deliberately not `with` — no startup
    assert not hasattr(main.app.state, "services")

    assert client.get("/v1/health").json()["status"] == "ok"
    assert client.get("/v1/capabilities").json()["demo_mode"] is True
    assert client.get("/v1/privacy/policy").status_code == 200

    # and a full upload still completes on that host
    accepted = client.post(
        "/v1/jobs",
        files={"file": ("meeting.mp4", b"RIFF$\x00\x00\x00WAVEfmt ", "video/mp4")},
        data={"consent": "true"},
    ).json()
    assert accepted["state"] == "completed"
    assert accepted["result"]["transcript"]["utterances"]

    config.get_settings.cache_clear()


def test_the_serverless_build_declares_that_it_keeps_nothing(serverless_client):
    """On a serverless host the container's storage goes with the request, so
    a later call cannot reach the job — as `test_a_second_invocation_cannot_see
    _the_first_ones_job` below demonstrates. The interface has to be told, or
    its export and delete buttons call an endpoint that answers 404."""
    capabilities = serverless_client.get("/v1/capabilities").json()
    assert capabilities["persistent_jobs"] is False


def test_the_normal_build_declares_that_it_does_keep_jobs(client):
    assert client.get("/v1/capabilities").json()["persistent_jobs"] is True


def test_a_second_invocation_cannot_see_the_first_ones_job(tmp_path, monkeypatch):
    """Each serverless request is a fresh container with an empty data
    directory. This is the reason the interface must not offer a server-side
    export or a delete button on that deployment."""
    import importlib

    from fastapi.testclient import TestClient

    from app.core.crypto import generate_service_key

    def invocation(name):
        monkeypatch.setenv("SYNCHRONOUS_JOBS", "true")
        monkeypatch.setenv("DEMO_MODE_LITE", "true")
        monkeypatch.setenv("AUDIT_LOG_ENABLED", "false")
        monkeypatch.setenv("DATA_DIR", str(tmp_path / name))
        monkeypatch.setenv("ENCRYPTION_KEY", generate_service_key())

        import app.config as config

        config.get_settings.cache_clear()
        import app.main as main

        importlib.reload(main)
        return TestClient(main.app)

    with invocation("first") as first:
        accepted = first.post(
            "/v1/jobs",
            files={"file": ("meeting.wav", b"RIFF$\x00\x00\x00WAVEfmt ", "audio/wav")},
            data={"consent": "true"},
        ).json()

    # the whole result came back in that one response — nothing is lost
    assert accepted["result"]["transcript"]["utterances"]

    headers = {"Authorization": f"Bearer {accepted['access_token']}"}
    with invocation("second") as second:
        assert second.get(f"/v1/jobs/{accepted['job_id']}/transcript.md", headers=headers).status_code == 404
        assert second.delete(f"/v1/jobs/{accepted['job_id']}", headers=headers).status_code == 404

    import app.config as config

    config.get_settings.cache_clear()


def test_the_interface_keys_export_and_delete_off_persistence():
    """The guard has to be on `persistent`, not on `live` — a serverless build
    is live and still cannot answer for a job after the response."""
    script = (ROOT / "app" / "web" / "app.js").read_text(encoding="utf-8")

    assert "state.persistent = capabilities.persistent_jobs !== false" in script
    assert "state.live && state.job && state.persistent" in script
    assert "if (state.live && state.job) {" not in script


def test_the_serverless_build_advertises_the_hosts_real_upload_limit():
    """Vercel rejects a request body over 4.5 MB at the edge, before the
    function runs. Advertising the repository default of 200 MB would mean the
    interface accepts a file, uploads it, and receives a platform error this
    service never saw and cannot explain."""
    entry = (ROOT / "api" / "index.py").read_text(encoding="utf-8")
    assert 'setdefault("MAX_UPLOAD_MB", "4")' in entry


def test_the_interface_refuses_an_oversized_file_before_uploading_it():
    script = (ROOT / "app" / "web" / "app.js").read_text(encoding="utf-8")
    assert "function rejectReason" in script
    assert "limits.max_upload_mb" in script
    assert "limits.allowed_extensions" in script
    # and a refused file must not stay armed for sending
    assert "state.file = refusal ? null : file" in script


def test_the_serverless_build_still_enforces_consent(serverless_client):
    response = serverless_client.post(
        "/v1/jobs",
        files={"file": ("meeting.wav", b"RIFF", "audio/wav")},
        data={"consent": "false"},
    )
    assert response.status_code == 403


def test_the_serverless_build_still_says_it_is_running_scripted_models(serverless_client):
    """The interface reads this and badges itself. Telling someone a scripted
    sample is their meeting would be a lie."""
    assert serverless_client.get("/v1/capabilities").json()["demo_mode"] is True


def test_the_entry_point_reports_why_it_failed_instead_of_a_blank_500(monkeypatch, tmp_path):
    """When the bundle cannot import the service, every route answers 500 with
    no body and the interface can only say "no API is reachable" — true and
    useless. The entry point serves the import error instead, so the failure
    can be read from a browser rather than guessed at."""
    import importlib.util
    import json

    monkeypatch.setenv("DATA_DIR", str(tmp_path / "broken"))
    # Make the import of the service fail the way a bad bundle does.
    monkeypatch.setitem(sys.modules, "app.main", None)

    spec = importlib.util.spec_from_file_location("vercel_entry_broken", ROOT / "api" / "index.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    received = []

    async def send(message):
        received.append(message)

    async def receive():
        return {"type": "http.request"}

    asyncio.run(module.app({"type": "http", "method": "GET", "path": "/v1/capabilities"}, receive, send))

    assert received[0]["status"] == 503
    body = json.loads(received[1]["body"])
    assert body["error"] == "service_unavailable"
    assert body["cause"], "the import error itself has to be in the response"
    assert body["python"]


def test_the_vercel_entry_point_imports_and_exposes_the_app(monkeypatch, tmp_path):
    """Loaded by path, the way Vercel loads it — `api/` is a function
    directory, not an importable package."""
    import importlib.util

    monkeypatch.setenv("DATA_DIR", str(tmp_path / "vercel"))

    spec = importlib.util.spec_from_file_location("vercel_entry", ROOT / "api" / "index.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    assert hasattr(module, "app"), "Vercel expects a module-level `app`"
    # The entry point is what puts the deployment into its serverless shape.
    assert module.os.environ["SYNCHRONOUS_JOBS"] == "true"
    assert module.os.environ["ENCRYPTION_KEY"]
