"""Regenerate the offline sample shown by "See a finished example".

    python -m tools.make_demo

The sample is not written by hand. It is produced by running the scripted
meeting through the same code the service runs — the aligner, the redactor,
the extractive summariser and the grounding verifier — so the example in the
interface cannot drift away from what the pipeline actually does. If a change
to the aligner alters the demo, that shows up as a diff in `demo-data.js`.

Writes `app/web/demo-data.js`, then mirrors `app/web/` into `public/` so the
edge-served copy stays byte-identical.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.config import Settings  # noqa: E402
from app.pipeline import fixtures  # noqa: E402
from app.pipeline.alignment import build_transcript, to_dicts  # noqa: E402
from app.pipeline.grounding_core import GroundingOptions, drop_ungrounded, verify_brief  # noqa: E402
from app.pipeline.redaction import redact_utterances  # noqa: E402
from app.pipeline.summarizer import ExtractiveSummarizer  # noqa: E402
from app.schemas import (  # noqa: E402
    ASRResult,
    ASRSegment,
    DiarizationResult,
    MeetingBrief,
    SpeakerTurn,
    Utterance,
    Word,
)

TARGET = ROOT / "app" / "web" / "demo-data.js"
HEADER = (
    "// Generated by `python -m tools.make_demo` — do not edit by hand.\n"
    "// Scripted audio in, genuine aligner and verifier output out.\n"
    "window.VOCALYZE_DEMO = "
)


def build() -> dict:
    settings = Settings()

    asr = ASRResult(
        language="en",
        duration=fixtures.total_duration(),
        segments=[
            ASRSegment(
                start=segment["start"],
                end=segment["end"],
                text=segment["text"],
                confidence=segment["confidence"],
                words=[Word(**word) for word in segment["words"]],
            )
            for segment in fixtures.build_segments()
        ],
        model="scripted-sample",
        backend="mock",
    )
    turns = fixtures.build_turns()
    diarization = DiarizationResult(
        turns=[SpeakerTurn(**turn) for turn in turns],
        num_speakers=len({turn["speaker"] for turn in turns}),
        model="scripted-sample",
        backend="mock",
    )

    transcript, stats = build_transcript(asr, diarization)

    utterance_dicts = to_dicts(transcript)
    redactions = redact_utterances(utterance_dicts)
    if redactions.count:
        transcript.utterances = [Utterance(**item) for item in utterance_dicts]

    utterances = to_dicts(transcript)
    raw = ExtractiveSummarizer(settings).summarize(utterances, transcript.language)
    verified, grounding = verify_brief(
        dict(raw), utterances, GroundingOptions(min_overlap=settings.min_evidence_overlap)
    )
    verified, dropped = drop_ungrounded(verified)

    brief = MeetingBrief(
        summary=verified.get("summary", ""),
        summary_evidence=verified.get("summary_evidence", {}),
        key_points=verified.get("key_points", []),
        decisions=verified.get("decisions", []),
        action_items=verified.get("action_items", []),
        dropped_claims=dropped,
        backend="extractive",
        model="rule-based",
    )

    confidences = [u.confidence for u in transcript.utterances if u.confidence is not None]
    quality = {
        "asr_mean_confidence": round(sum(confidences) / len(confidences), 3) if confidences else None,
        "low_confidence_utterances": sum(1 for c in confidences if c < 0.6),
        "speaker_count": len([s for s in transcript.speakers if s != "UNKNOWN"]),
        "overlapped_utterances": stats.overlapped_utterances,
        "unassigned_speech_seconds": stats.unassigned_speech_seconds,
        "grounded_claims": grounding["grounded"],
        "dropped_claims": dropped,
        "redactions": redactions.count,
    }

    return {
        "job": {
            "id": "demo",
            "state": "completed",
            "filename": "team-standup.m4a",
            "size_bytes": 8412160,
            "duration_seconds": round(transcript.duration, 2),
            "progress": 1.0,
        },
        "transcript": transcript.model_dump(mode="json"),
        "brief": brief.model_dump(mode="json"),
        "quality": quality,
        "privacy": {
            "consent": True,
            "redact_pii": settings.redact_pii,
            "delete_audio_after_asr": settings.delete_audio_after_asr,
            "retention_hours": settings.retention_hours,
            "audio_retained": False,
            "encrypted_at_rest": True,
            "expires_at": None,
            "models": {
                "asr": {"backend": "mock", "model": "scripted-sample"},
                "diarization": {"backend": "mock", "model": "scripted-sample"},
                "summarizer": {"backend": "extractive", "model": "rule-based"},
            },
        },
    }


def main() -> None:
    payload = build()
    TARGET.write_text(HEADER + json.dumps(payload, indent=1, ensure_ascii=False) + ";\n", encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)} — {len(payload['transcript']['utterances'])} utterances.")

    from scripts.build_static import main as mirror

    mirror()


if __name__ == "__main__":
    main()
