/* Hash-chained audit trail, in the browser.
 *
 * A port of `app/core/audit.py`. Each entry carries the SHA-256 of the entry
 * before it, so editing or removing one breaks the chain and the verifier says
 * where. The chain detects tampering; it does not prevent it. Detection is
 * what can honestly be offered, on a server or here.
 *
 * The point of running it in the page is that the audit trail stays real. A
 * static build could show a picture of one — this one is generated by the run
 * you just did, and the verify button recomputes every hash in front of you.
 *
 * Content is never recorded: field names are checked and anything that looks
 * like transcript text is dropped, so the trail stays safe to keep after the
 * transcript is gone.
 */

(function (global) {
  'use strict';

  const ZERO = '0'.repeat(64);
  const FORBIDDEN = new Set(['text', 'transcript', 'utterance', 'summary', 'content', 'body']);
  const STORAGE_KEY = 'vocalyze.audit';

  async function sha256(value) {
    const bytes = new TextEncoder().encode(value);
    const digest = await crypto.subtle.digest('SHA-256', bytes);
    return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
  }

  /* Byte-for-byte what `json.dumps(sort_keys=True)` produces, because that is
   * what the Python side hashes: keys sorted, and its default separators —
   * ", " and ": ", spaces included. Drop the spaces and every hash differs,
   * which would make this a lookalike rather than the same chain. */
  function canonical(value) {
    if (value === null || typeof value !== 'object') return JSON.stringify(value);
    if (Array.isArray(value)) return `[${value.map(canonical).join(', ')}]`;
    const keys = Object.keys(value).sort();
    return `{${keys.map((k) => `${JSON.stringify(k)}: ${canonical(value[k])}`).join(', ')}}`;
  }

  function sanitise(details) {
    const clean = {};
    for (const [key, value] of Object.entries(details || {})) {
      if (FORBIDDEN.has(key.toLowerCase())) continue;
      clean[key] = typeof value === 'string' && value.length > 300
        ? `${value.slice(0, 300)}…`
        : value;
    }
    return clean;
  }

  const lineHash = (entry) => sha256(canonical({
    ts: entry.ts, action: entry.action, details: entry.details, prev: entry.prev,
  }));

  function load() {
    try {
      return JSON.parse(sessionStorage.getItem(STORAGE_KEY) || '[]');
    } catch (error) {
      return [];
    }
  }

  function save(entries) {
    try {
      // sessionStorage, not localStorage: the trail describes this session's
      // run and should not outlive the tab any more than the transcript does.
      sessionStorage.setItem(STORAGE_KEY, JSON.stringify(entries));
    } catch (error) {
      // A full or disabled store must not take the transcription down with it.
      console.warn('[vocalyze] audit trail not persisted:', error.message);
    }
  }

  async function record(action, details) {
    const entries = load();
    const prev = entries.length ? entries[entries.length - 1].hash : ZERO;
    const entry = {
      ts: new Date().toISOString(),
      action,
      details: sanitise(details),
      prev,
    };
    entry.hash = await lineHash(entry);
    entries.push(entry);
    save(entries);
    return entry;
  }

  /* Recompute the whole chain. Returns where it breaks, not just whether. */
  async function verify() {
    const entries = load();
    let prev = ZERO;
    for (let index = 0; index < entries.length; index += 1) {
      const entry = entries[index];
      if (entry.prev !== prev) {
        return { intact: false, checked: index, reason: `entry ${index + 1} does not follow the one before it` };
      }
      if (await lineHash(entry) !== entry.hash) {
        return { intact: false, checked: index, reason: `entry ${index + 1} has been altered since it was written` };
      }
      prev = entry.hash;
    }
    return { intact: true, checked: entries.length, reason: '' };
  }

  function clear() {
    try { sessionStorage.removeItem(STORAGE_KEY); } catch (error) { /* nothing to clear */ }
  }

  global.VocalyzeAudit = { record, verify, entries: load, clear, sha256, canonical, ZERO };
}(typeof globalThis !== 'undefined' ? globalThis : this));
