// Generated by `python -m tools.make_demo` — do not edit by hand.
// Scripted audio in, genuine aligner and verifier output out.
window.VOCALYZE_DEMO = {
 "job": {
  "id": "demo",
  "state": "completed",
  "filename": "team-standup.m4a",
  "size_bytes": 8412160,
  "duration_seconds": 112.54,
  "progress": 1.0
 },
 "transcript": {
  "language": "en",
  "duration": 112.54,
  "speakers": [
   "SPEAKER_00",
   "SPEAKER_01",
   "SPEAKER_02",
   "SPEAKER_03"
  ],
  "utterances": [
   {
    "id": "u1",
    "speaker": "SPEAKER_00",
    "start": 1.2,
    "end": 4.195,
    "text": "Alright, let's start with where the dataset stands.",
    "confidence": 0.877,
    "speaker_confidence": 1.0,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u2",
    "speaker": "SPEAKER_01",
    "start": 4.673,
    "end": 22.177,
    "text": "AMI and ICSI are both downloaded and cleaned. We are at ninety hours after removing the corrupted sessions. Everything is resampled to sixteen kilohertz mono, and the split is speaker disjoint, so no speaker appears in both train and test.",
    "confidence": 0.909,
    "speaker_confidence": 0.987,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u3",
    "speaker": "SPEAKER_00",
    "start": 22.657,
    "end": 25.456,
    "text": "Good. Any sessions we had to throw away?",
    "confidence": 0.898,
    "speaker_confidence": 0.898,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u4",
    "speaker": "SPEAKER_01",
    "start": 25.942,
    "end": 30.957,
    "text": "Four ICSI sessions had broken timestamps. They are documented in the dataset card.",
    "confidence": 0.887,
    "speaker_confidence": 0.997,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u5",
    "speaker": "SPEAKER_02",
    "start": 31.442,
    "end": 48.509,
    "text": "On the recognition side, Whisper large is running on the clean split. Word error rate is eleven point two percent, down from eighteen point four on the raw audio. Most of the remaining errors are crosstalk, where two people speak at once.",
    "confidence": 0.912,
    "speaker_confidence": 1.0,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u6",
    "speaker": "SPEAKER_03",
    "start": 48.984,
    "end": 57.106,
    "text": "Diarization has the same problem. Speaker error rate is around nine percent, and almost all of it is in the overlap regions.",
    "confidence": 0.915,
    "speaker_confidence": 0.979,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u7",
    "speaker": "SPEAKER_00",
    "start": 57.587,
    "end": 64.833,
    "text": "So both models fail in the same place. Can we handle overlap once, in the merge step, instead of twice?",
    "confidence": 0.918,
    "speaker_confidence": 1.0,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u8",
    "speaker": "SPEAKER_03",
    "start": 65.318,
    "end": 73.628,
    "text": "That is what I would suggest. Flag the overlapped spans and let the interface show them as uncertain rather than guessing a speaker.",
    "confidence": 0.915,
    "speaker_confidence": 1.0,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u9",
    "speaker": "SPEAKER_02",
    "start": 74.111,
    "end": 76.42,
    "text": "Right, uncertain is better than confidently wrong.",
    "confidence": 0.906,
    "speaker_confidence": 1.0,
    "overlapped": true,
    "redacted": false
   },
   {
    "id": "u10",
    "speaker": "SPEAKER_00",
    "start": 76.894,
    "end": 81.954,
    "text": "Agreed. We flag overlap in the interface instead of forcing a single speaker.",
    "confidence": 0.884,
    "speaker_confidence": 0.977,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u11",
    "speaker": "SPEAKER_02",
    "start": 82.438,
    "end": 87.657,
    "text": "For the summary, we should require the model to quote the line it took each point from.",
    "confidence": 0.912,
    "speaker_confidence": 1.0,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u12",
    "speaker": "SPEAKER_01",
    "start": 88.133,
    "end": 93.313,
    "text": "That also gives us a check. If the quoted line does not exist, we drop the point.",
    "confidence": 0.911,
    "speaker_confidence": 0.969,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u13",
    "speaker": "SPEAKER_00",
    "start": 93.791,
    "end": 99.338,
    "text": "Let's do that. Rima will wire the evidence check into the pipeline before Thursday.",
    "confidence": 0.895,
    "speaker_confidence": 0.97,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u14",
    "speaker": "SPEAKER_03",
    "start": 99.823,
    "end": 104.681,
    "text": "I can have it ready Wednesday if the transcript format is frozen today.",
    "confidence": 0.887,
    "speaker_confidence": 0.967,
    "overlapped": false,
    "redacted": false
   },
   {
    "id": "u15",
    "speaker": "SPEAKER_00",
    "start": 105.16,
    "end": 111.538,
    "text": "Consider it frozen. Saad, you write the report against this format, and we submit Sunday.",
    "confidence": 0.91,
    "speaker_confidence": 0.966,
    "overlapped": false,
    "redacted": false
   }
  ]
 },
 "brief": {
  "summary": "AMI and ICSI are both downloaded and cleaned. Agreed. We flag overlap in the interface instead of forcing a single speaker. Let's do that. Rima will wire the evidence check into the pipeline before Thursday.",
  "summary_evidence": {
   "utterance_ids": [
    "u2",
    "u10",
    "u13"
   ],
   "grounding": 1.0,
   "verified": true
  },
  "key_points": [
   {
    "text": "AMI and ICSI are both downloaded and cleaned.",
    "evidence": {
     "utterance_ids": [
      "u2"
     ],
     "grounding": 1.0,
     "verified": true
    }
   },
   {
    "text": "On the recognition side, Whisper large is running on the clean split.",
    "evidence": {
     "utterance_ids": [
      "u5"
     ],
     "grounding": 1.0,
     "verified": true
    }
   },
   {
    "text": "Diarization has the same problem. Speaker error rate is around nine percent, and almost all of it is in the overlap regions.",
    "evidence": {
     "utterance_ids": [
      "u6"
     ],
     "grounding": 1.0,
     "verified": true
    }
   },
   {
    "text": "So both models fail in the same place. Can we handle overlap once, in the merge step, instead of twice?",
    "evidence": {
     "utterance_ids": [
      "u7"
     ],
     "grounding": 1.0,
     "verified": true
    }
   },
   {
    "text": "For the summary, we should require the model to quote the line it took each point from.",
    "evidence": {
     "utterance_ids": [
      "u11"
     ],
     "grounding": 1.0,
     "verified": true
    }
   }
  ],
  "decisions": [
   {
    "text": "Agreed. We flag overlap in the interface instead of forcing a single speaker.",
    "evidence": {
     "utterance_ids": [
      "u10"
     ],
     "grounding": 1.0,
     "verified": true
    }
   }
  ],
  "action_items": [
   {
    "text": "Let's do that. Rima will wire the evidence check into the pipeline before Thursday.",
    "evidence": {
     "utterance_ids": [
      "u13"
     ],
     "grounding": 1.0,
     "verified": true
    },
    "owner": "Rima",
    "due": "Thursday"
   },
   {
    "text": "I can have it ready Wednesday if the transcript format is frozen today.",
    "evidence": {
     "utterance_ids": [
      "u14"
     ],
     "grounding": 1.0,
     "verified": true
    },
    "owner": "the speaker",
    "due": "Wednesday"
   },
   {
    "text": "Consider it frozen. Saad, you write the report against this format, and we submit Sunday.",
    "evidence": {
     "utterance_ids": [
      "u15"
     ],
     "grounding": 1.0,
     "verified": true
    },
    "owner": "Saad",
    "due": null
   }
  ],
  "dropped_claims": 0,
  "model": "rule-based",
  "backend": "extractive"
 },
 "quality": {
  "asr_mean_confidence": 0.902,
  "low_confidence_utterances": 0,
  "speaker_count": 4,
  "overlapped_utterances": 1,
  "unassigned_speech_seconds": 0.0,
  "grounded_claims": 9,
  "dropped_claims": 0,
  "redactions": 0
 },
 "privacy": {
  "consent": true,
  "redact_pii": true,
  "delete_audio_after_asr": true,
  "retention_hours": 24,
  "audio_retained": false,
  "encrypted_at_rest": true,
  "expires_at": null,
  "models": {
   "asr": {
    "backend": "mock",
    "model": "scripted-sample"
   },
   "diarization": {
    "backend": "mock",
    "model": "scripted-sample"
   },
   "summarizer": {
    "backend": "extractive",
    "model": "rule-based"
   }
  }
 }
};
